package com.klynstudios.hapture.data

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

@Dao
interface ExperimentDao {
    // Pinned rows first (a pinned newer-looking row never buries an older
    // pinned one), each group most-recently-updated first.
    @Query("SELECT * FROM experiments ORDER BY pinned DESC, updatedAt DESC")
    fun observeAll(): Flow<List<ExperimentEntity>>

    @Query("SELECT * FROM experiments WHERE id = :id")
    suspend fun getById(id: Long): ExperimentEntity?

    /**
     * For a brand-new row only (id = 0, autogenerated). [OnConflictStrategy.REPLACE]
     * is SQLite's delete-then-reinsert, not a true update -- calling this on an
     * *existing* id would cascade-delete anything with an `ON DELETE CASCADE`
     * foreign key pointing at it (a timeline step referencing this experiment,
     * for instance). Updating an existing row must go through [update] instead.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(entity: ExperimentEntity): Long

    /** A true SQL UPDATE by primary key -- safe for an existing row with foreign-key children. */
    @Update
    suspend fun update(entity: ExperimentEntity)

    @Query("SELECT COUNT(*) FROM experiments WHERE type = :type")
    suspend fun countByType(type: ExperimentType): Int

    @Delete
    suspend fun delete(entity: ExperimentEntity)

    /**
     * Re-inserts a just-deleted entity with its own original id, for Undo.
     * Safe as [upsert] here specifically because the row doesn't exist at this
     * point (it was just deleted) -- there's nothing for REPLACE to conflict
     * with or cascade away. Any timeline step that referenced this experiment
     * was already cascade-deleted along with it and is not restored; see
     * [com.klynstudios.hapture.data.ExperimentRepository.restore].
     */
    suspend fun restore(entity: ExperimentEntity) {
        upsert(entity)
    }
}
