package com.motionlab.app.export.platform

import com.motionlab.app.core.spec.MotionSpec
import com.motionlab.app.core.spec.MotionTransition
import com.motionlab.app.export.DesignSpec

internal fun n(v: Float, d: Int = 3) = DesignSpec.num(v, d)

internal fun pascal(name: String): String =
    name.split(Regex("[^A-Za-z0-9]+")).filter { it.isNotEmpty() }.joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
        .ifEmpty { "Motion" }.let { if (it[0].isDigit()) "M$it" else it }

internal fun camel(name: String): String = pascal(name).replaceFirstChar { it.lowercase() }

internal fun header(spec: MotionSpec, comment: String): String =
    "$comment Generated by Motion Lab -- ${spec.name}\n" +
        "$comment ${spec.interaction} / trigger: ${spec.trigger}. Spring: stiffness ${n(spec.spring.stiffness, 1)}, " +
        "damping ${n(spec.spring.damping, 2)} (ratio ${n(spec.spring.dampingRatio, 2)}), mass ${n(spec.spring.mass)}. " +
        "Settles in ~${spec.spring.settleMs} ms, overshoot ${n(spec.spring.overshootPercent, 1)}%.\n" +
        (spec.parameters["staggerMs"]?.let { "$comment Stagger: item i starts ${n(it, 0)} ms * i after the trigger (${n(spec.parameters["itemCount"] ?: 1f, 0)} items).\n" } ?: "")

internal fun MotionTransition.isDp() = property == "offsetX" || property == "offsetY"
