package com.klynstudios.hapture.export

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. A card that grows into a full page, written
 * the way Compose does it natively: `SharedTransitionLayout` + `AnimatedContent`, with the tuned spring as
 * the bounds transform. The contents fade through (card out over the first half, page in over the second),
 * and the corners straighten on the same spring, matching the editor's preview.
 */
object CardExpandCodeGenerator {

    fun generate(stiffness: Float, dampingRatio: Float, cornerDp: Float, fadeMs: Float): String {
        val k = DesignSpec.num(stiffness, 1)
        val z = DesignSpec.num(dampingRatio, 2)
        val corner = DesignSpec.num(cornerDp, 1)
        val half = (fadeMs / 2f).toInt().coerceAtLeast(1)

        return """
            |// Generated by Hapture -- a card that grows into a full page (container transform) and back.
            |// Swap the two placeholder boxes for your card and your detail screen.
            |${ComposeImports.GESTURE}
            |import androidx.compose.animation.*
            |
            |@OptIn(ExperimentalSharedTransitionApi::class, ExperimentalAnimationApi::class)
            |@Composable
            |fun HaptureCardExpand(modifier: Modifier = Modifier, color: Color = Color(0xFFE7E5E0)) {
            |    var open by remember { mutableStateOf(false) }
            |    val cornerDp = ${corner}f
            |    val bounds = BoundsTransform { _, _ ->
            |        spring(dampingRatio = ${z}f, stiffness = ${k}f, visibilityThreshold = Rect.VisibilityThreshold)
            |    }
            |
            |    SharedTransitionLayout(modifier) {
            |        AnimatedContent(
            |            targetState = open,
            |            // The shared bounds do the moving; the screens themselves just swap.
            |            transitionSpec = { EnterTransition.None togetherWith ExitTransition.None },
            |            label = "cardExpand",
            |        ) { isOpen ->
            |            // Rounded as a card, square as a page, on the same spring as the bounds.
            |            val corner by transition.animateDp(
            |                transitionSpec = { spring(dampingRatio = ${z}f, stiffness = ${k}f) },
            |                label = "corner",
            |            ) { state -> if (isOpen && state == EnterExitState.Visible) 0.dp else cornerDp.dp }
            |            val shape = RoundedCornerShape(corner.coerceAtLeast(0.dp))
            |
            |            Box(Modifier.fillMaxSize().padding(if (isOpen) 0.dp else 16.dp)) {
            |                Box(
            |                    Modifier
            |                        .testTag(if (isOpen) "haptureExpandPage" else "haptureExpandCard")
            |                        .sharedBounds(
            |                            rememberSharedContentState(key = "card"),
            |                            animatedVisibilityScope = this@AnimatedContent,
            |                            // Fade through: the card's contents leave in the first half, the page's arrive in the second.
            |                            enter = fadeIn(tween(durationMillis = $half, delayMillis = $half)),
            |                            exit = fadeOut(tween(durationMillis = $half)),
            |                            boundsTransform = bounds,
            |                            resizeMode = SharedTransitionScope.ResizeMode.RemeasureToBounds,
            |                            clipInOverlayDuringTransition = OverlayClip(shape),
            |                        )
            |                        .then(if (isOpen) Modifier.fillMaxSize() else Modifier.size(160.dp, 112.dp))
            |                        .clip(shape)
            |                        .background(color)
            |                        .clickable { open = !isOpen },
            |                ) {
            |                    // Your card or detail content goes here.
            |                }
            |            }
            |        }
            |    }
            |}
        """.trimMargin()
    }
}
