package com.klynstudios.hapture.export

import org.json.JSONArray
import org.json.JSONObject

/**
 * Just the buzz pattern of a timeline, without any visual motion, for teams that
 * want the haptics alone. The pulse table mirrors what the app itself plays
 * ([com.klynstudios.hapture.core.haptics.HapticEngine]) so what you felt is what ships.
 */
object HapticExport {

    /** One physical pulse. [amplitude] is Android's 1..255; iOS uses [intensity] and [sharpness] in 0..1. */
    private data class Pulse(val durationMs: Int, val amplitude: Int, val intensity: Double, val sharpness: Double)

    private val SOFT = Pulse(8, 40, 0.30, 0.20)
    private val TICK = Pulse(8, 90, 0.50, 0.60)
    private val CLICK = Pulse(14, 120, 0.60, 0.80)
    private val IMPACT = Pulse(20, 200, 0.90, 0.50)
    private val HEAVY = Pulse(32, 255, 1.00, 0.30)
    private val SUCCESS = Pulse(16, 150, 0.70, 0.60)
    private const val SUCCESS_GAP_MS = 60

    /** Pulses in time order as (startMs, pulse). "success" is a double tap. */
    private fun pulses(haptics: List<TimelineSpec.Haptic>): List<Pair<Int, Pulse>> =
        haptics.sortedBy { it.timeMs }.flatMap { h ->
            when (h.effect.lowercase()) {
                "soft" -> listOf(h.timeMs to SOFT)
                "click" -> listOf(h.timeMs to CLICK)
                "impact" -> listOf(h.timeMs to IMPACT)
                "heavy" -> listOf(h.timeMs to HEAVY)
                "success" -> listOf(h.timeMs to SUCCESS, h.timeMs + SUCCESS_GAP_MS to SUCCESS)
                else -> listOf(h.timeMs to TICK)
            }
        }.sortedBy { it.first }

    private fun none(name: String) = "// $name has no haptic markers yet. Add some on the timeline first.\n"

    /** A `VibrationEffect.createWaveform` snippet: off/on timings and amplitudes. */
    fun android(name: String, haptics: List<TimelineSpec.Haptic>): String {
        if (haptics.isEmpty()) return none(name)
        val timings = ArrayList<Long>()
        val amps = ArrayList<Int>()
        var cursor = 0
        pulses(haptics).forEach { (at, p) ->
            timings += maxOf(0, at - cursor).toLong(); amps += 0
            timings += p.durationMs.toLong(); amps += p.amplitude
            cursor = maxOf(cursor, at) + p.durationMs
        }
        return """
            |// Generated by Hapture: haptics for "${name.replace("\"", "'")}" (${haptics.size} markers, $cursor ms)
            |import android.os.VibrationEffect
            |import android.os.Vibrator
            |
            |// Off/on pairs in milliseconds, then the strength of each "on" (0 = silent, 255 = full).
            |val hapticPattern: VibrationEffect = VibrationEffect.createWaveform(
            |    longArrayOf(${timings.joinToString(", ")}),
            |    intArrayOf(${amps.joinToString(", ")}),
            |    -1, // play once
            |)
            |
            |// vibrator.vibrate(hapticPattern)
            |// API 26+. On motors without amplitude control (vibrator.hasAmplitudeControl() is false)
            |// every non-zero amplitude plays at the same strength, so the pulses become on/off taps.
        """.trimMargin() + "\n"
    }

    /** CoreHaptics Swift that plays the pattern as transient taps. */
    fun coreHaptics(name: String, haptics: List<TimelineSpec.Haptic>): String {
        if (haptics.isEmpty()) return none(name)
        val events = pulses(haptics).joinToString("\n") { (at, p) ->
            "        CHHapticEvent(eventType: .hapticTransient, parameters: [\n" +
                "            CHHapticEventParameter(parameterID: .hapticIntensity, value: ${DesignSpec.num(p.intensity.toFloat(), 2)}),\n" +
                "            CHHapticEventParameter(parameterID: .hapticSharpness, value: ${DesignSpec.num(p.sharpness.toFloat(), 2)}),\n" +
                "        ], relativeTime: ${DesignSpec.num(at / 1000f, 3)}),"
        }
        return """
            |// Generated by Hapture: haptics for "${name.replace("\"", "'")}" (${haptics.size} markers)
            |import CoreHaptics
            |
            |func playHaptics(on engine: CHHapticEngine) throws {
            |    let events: [CHHapticEvent] = [
            |$events
            |    ]
            |    let pattern = try CHHapticPattern(events: events, parameters: [])
            |    let player = try engine.makePlayer(with: pattern)
            |    try player.start(atTime: CHHapticTimeImmediate)
            |}
            |
            |// Once, at launch:
            |//   guard CHHapticEngine.capabilitiesForHardware().supportsHaptics else { return }
            |//   let engine = try CHHapticEngine(); try engine.start()
        """.trimMargin() + "\n"
    }

    /** An Apple Haptic and Audio Pattern (.ahap) file, loadable with `CHHapticEngine.playPattern(from:)`. */
    fun ahap(name: String, haptics: List<TimelineSpec.Haptic>): String {
        val pattern = JSONArray()
        pulses(haptics).forEach { (at, p) ->
            pattern.put(
                JSONObject().put(
                    "Event",
                    JSONObject().put("Time", at / 1000.0).put("EventType", "HapticTransient").put(
                        "EventParameters",
                        JSONArray()
                            .put(JSONObject().put("ParameterID", "HapticIntensity").put("ParameterValue", p.intensity))
                            .put(JSONObject().put("ParameterID", "HapticSharpness").put("ParameterValue", p.sharpness))
                    )
                )
            )
        }
        return JSONObject().put("Version", 1.0).put("Metadata", JSONObject().put("Project", name)).put("Pattern", pattern).toString(2)
    }
}
