package com.klynstudios.hapture.export

import com.klynstudios.hapture.core.physics.PredictiveBackSolver

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. The page transform is the one
 * [PredictiveBackSolver] drives the preview with, written out inline; the swipe progress comes
 * from the system through `PredictiveBackHandler`, and the tuned spring finishes the exit on
 * commit or brings the page back on cancel.
 */
object PredictiveBackCodeGenerator {

    fun generate(stiffness: Float, dampingRatio: Float, minScale: Float, shiftFraction: Float): String {
        val stiffnessStr = DesignSpec.num(stiffness, 1)
        val dampingStr = DesignSpec.num(dampingRatio, 2)
        val scaleStr = DesignSpec.num(minScale, 3)
        val shiftStr = DesignSpec.num(shiftFraction, 3)
        val cornerStr = DesignSpec.num(PredictiveBackSolver.MAX_CORNER_DP, 0)

        return """
            |// Generated by Hapture -- predictive back: the page shrinks and leans toward the edge while you swipe,
            |// then a spring finishes the exit or brings it back. Needs android:enableOnBackInvokedCallback="true"
            |// on the <application> (or <activity>) in AndroidManifest.xml.
            |${ComposeImports.GESTURE}
            |import androidx.activity.BackEventCompat
            |import androidx.activity.compose.PredictiveBackHandler
            |import kotlin.coroutines.cancellation.CancellationException
            |
            |@Composable
            |fun HapturePredictiveBack(onBack: () -> Unit, modifier: Modifier = Modifier, content: @Composable () -> Unit) {
            |    val minScale = ${scaleStr}f
            |    val shiftFraction = ${shiftStr}f
            |    val settle = spring<Float>(dampingRatio = ${dampingStr}f, stiffness = ${stiffnessStr}f)
            |    val progress = remember { Animatable(0f) }
            |    val exit = remember { Animatable(0f) }
            |    var fromLeft by remember { mutableStateOf(true) }
            |    val scope = rememberCoroutineScope()
            |
            |    PredictiveBackHandler { events ->
            |        try {
            |            events.collect { e ->
            |                fromLeft = e.swipeEdge == BackEventCompat.EDGE_LEFT
            |                progress.snapTo(e.progress)
            |            }
            |            // Committed: finish the exit on the tuned spring, then go back.
            |            exit.animateTo(1f, settle)
            |            onBack()
            |        } catch (e: CancellationException) {
            |            // Cancelled: spring back into place.
            |            scope.launch { progress.animateTo(0f, settle) }
            |            throw e
            |        }
            |    }
            |
            |    Box(
            |        modifier.graphicsLayer {
            |            val p = progress.value.coerceIn(0f, 1f)
            |            val s = 1f - (1f - minScale) * p
            |            val dir = if (fromLeft) 1f else -1f
            |            scaleX = s
            |            scaleY = s
            |            translationX = dir * size.width * (shiftFraction * p + exit.value)
            |            shape = RoundedCornerShape(${cornerStr}.dp.toPx() * (p * 5f).coerceAtMost(1f))
            |            clip = true
            |        },
            |    ) { content() }
            |}
        """.trimMargin()
    }
}
