package com.klynstudios.hapture.export

import kotlin.math.round

/**
 * Turns a tuned spring into a Compose snippet. The same input always gives the
 * same output, byte for byte. These are short snippets, so a string template is
 * simpler than KotlinPoet and easy to golden-test.
 *
 * The stiffness and damping ratio passed in are the exact values the editor's
 * live preview animates with. This only formats them and never recomputes them,
 * so the exported spring() matches what you felt on the phone.
 */
object SpringCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        resistanceK: Float,
        bound: Float,
    ): String {
        val stiffnessStr = formatFloat(stiffness)
        val dampingStr = formatFloat(dampingRatio)
        val kStr = formatFloat(resistanceK, decimals = 4)
        val boundStr = formatFloat(bound)

        return """
            |// Generated by Hapture -- drag-to-spring-back with rubber-band overscroll.
            |// Paste this HaptureRubberBandDrag() where you'd otherwise hand-roll drag physics.
            |${ComposeImports.GESTURE}
            |
            |private fun rubberBand(raw: Float, bound: Float, k: Float): Float {
            |    val clamped = raw.coerceIn(-bound, bound)
            |    val excess = raw - clamped
            |    return clamped + excess / (1 + k * kotlin.math.abs(excess))
            |}
            |
            |@Composable
            |fun HaptureRubberBandDrag(modifier: Modifier = Modifier) {
            |    val offsetX = remember { Animatable(0f) }
            |    val scope = rememberCoroutineScope()
            |    val bound = ${boundStr}f
            |    val resistanceK = ${kStr}f
            |
            |    Box(
            |        // offset/scale first, so whatever look you pass in modifier (size, background) moves with it.
            |        modifier = Modifier
            |            .offset { IntOffset(offsetX.value.roundToInt(), 0) }
            |            .then(modifier)
            |            .pointerInput(Unit) {
            |                var raw = 0f
            |                detectDragGestures(
            |                    onDragStart = { raw = offsetX.value },
            |                    onDrag = { change, dragAmount ->
            |                        change.consume()
            |                        raw += dragAmount.x
            |                        scope.launch {
            |                            offsetX.snapTo(rubberBand(raw, bound, resistanceK))
            |                        }
            |                    },
            |                    onDragEnd = {
            |                        scope.launch {
            |                            offsetX.animateTo(
            |                                targetValue = 0f,
            |                                animationSpec = spring(
            |                                    dampingRatio = ${dampingStr}f,
            |                                    stiffness = ${stiffnessStr}f
            |                                )
            |                            )
            |                            // Settled: fire your haptic here, e.g. HapticEngine.play(HapticEvent.Release)
            |                        }
            |                    }
            |                )
            |            }
            |    )
            |}
        """.trimMargin()
    }

    private fun formatFloat(value: Float, decimals: Int = 1): String {
        val factor = Math.pow(10.0, decimals.toDouble())
        val rounded = round(value * factor) / factor
        return if (decimals == 0) rounded.toInt().toString() else rounded.toString()
    }
}
