package com.motionlab.app.export

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import com.motionlab.app.core.haptics.HapticPreset
import com.motionlab.app.core.model.ObjectFill
import com.motionlab.app.core.model.ObjectStyle
import com.motionlab.app.ui.design.DesignTokens
import java.math.BigDecimal
import java.math.RoundingMode

/**
 * The hand-off formats: everything a designer needs to rebuild what you tuned
 * without opening Android Studio. Same policy as the Compose generators --
 * plain deterministic templates, numbers formatted at fixed precision, no
 * serialization dependency for a few small documents.
 */
object DesignSpec {

    /** Motion parameters as a designer sees them, on top of the shared spring. */
    data class Extra(val key: String, val value: Float)

    /**
     * One JSON document: the spring in Compose, Figma and CSS terms, the
     * interaction's own parameters, the object, and the theme it was tuned on.
     */
    fun json(
        name: String,
        interaction: String,
        stiffness: Float,
        dampingRatio: Float,
        extras: List<Extra>,
        style: ObjectStyle,
        tokens: DesignTokens,
        haptics: HapticPreset = HapticPreset.CRISP,
    ): String {
        val damping = SpringMath.damping(stiffness, dampingRatio)
        val settle = SpringMath.settleMs(stiffness, dampingRatio)
        val overshoot = SpringMath.overshoot(dampingRatio) * 100f
        val fillHex = hex(fillColor(style.fill, tokens))
        val customSvg = SvgPath.of(style.customPath)

        return """
            |{
            |  "tool": "Motion Lab",
            |  "specVersion": 1,
            |  "name": ${str(name)},
            |  "interaction": ${str(interaction)},
            |  "spring": {
            |    "mass": 1,
            |    "stiffness": ${num(stiffness)},
            |    "dampingRatio": ${num(dampingRatio)},
            |    "damping": ${num(damping)},
            |    "settleMs": $settle,
            |    "overshootPercent": ${num(overshoot)},
            |    "note": "Step 0 to 1, zero release velocity. Real drags add release velocity."
            |  },
            |  "figma": {
            |    "easing": "Custom spring",
            |    "mass": 1,
            |    "stiffness": ${num(stiffness)},
            |    "damping": ${num(damping)}
            |  },
            |  "compose": ${str("spring(dampingRatio = ${num(dampingRatio)}f, stiffness = ${num(stiffness)}f)")},
            |  "css": {
            |    "duration": "${settle}ms",
            |    "easing": ${str(cssLinear(stiffness, dampingRatio))}
            |  },
            |  "parameters": {${extras.joinToString(",") { "\n            |    ${str(it.key)}: ${num(it.value, 4)}" }}
            |  },
            |  "object": {
            |    "shape": ${str(style.shape.name.lowercase())},
            |    "sizeDp": ${num(style.sizeDp)},
            |    "fill": ${str(style.fill.name.lowercase())},
            |    "fillColor": "$fillHex",
            |    "strokeColor": "${hex(tokens.ink)}"${if (customSvg != null) ",\n            |    \"customPathSvg\": ${str(customSvg)},\n            |    \"customPathViewBox\": \"0 0 100 100\"" else ""}
            |  },
            |  "haptics": {
            |    "preset": ${str(haptics.name.lowercase())}${haptics.table().joinToString("") { ",\n            |    ${str(it.first)}: ${str(it.second)}" }}
            |  },
            |  "theme": ${str(tokens.id.name.lowercase())}
            |}
        """.trimMargin()
    }

    /** `linear(...)` easing reproducing the spring, for CSS transitions and web prototypes. */
    fun cssLinear(stiffness: Float, dampingRatio: Float): String =
        SpringMath.samples(stiffness, dampingRatio).joinToString(", ", "linear(", ")") { num(it, 3) }

    /** Ready-to-paste CSS custom properties. */
    fun css(name: String, stiffness: Float, dampingRatio: Float): String {
        val slug = name.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-').ifEmpty { "spring" }
        return """
            |/* Generated by Motion Lab -- $name */
            |:root {
            |  --$slug-duration: ${SpringMath.settleMs(stiffness, dampingRatio)}ms;
            |  --$slug-easing: ${cssLinear(stiffness, dampingRatio)};
            |}
            |/* usage: transition: transform var(--$slug-duration) var(--$slug-easing); */
        """.trimMargin()
    }

    fun fillColor(fill: ObjectFill, tokens: DesignTokens): Color = when (fill) {
        ObjectFill.INK -> tokens.ink
        ObjectFill.MARKER -> tokens.accent
        ObjectFill.PAPER -> tokens.surface
    }

    internal fun hex(color: Color): String = "#%06X".format(color.toArgb() and 0xFFFFFF)

    internal fun num(value: Float, decimals: Int = 3): String =
        BigDecimal(value.toDouble()).setScale(decimals, RoundingMode.HALF_UP).stripTrailingZeros().toPlainString()

    internal fun str(value: String): String = buildString {
        append('"')
        for (c in value) when (c) {
            '"' -> append("\\\"")
            '\\' -> append("\\\\")
            '\n' -> append("\\n")
            else -> append(c)
        }
        append('"')
    }
}
