package com.motionlab.app.export

import kotlin.math.round

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. The
 * magnetic-pull and nearest-target math emitted here is copy-pasted
 * verbatim from [com.motionlab.app.core.physics.MagneticSolver] and
 * [com.motionlab.app.core.physics.SnapPoints] -- one formula, two call
 * sites, so preview and export can't drift apart.
 */
object MagneticSnapCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        magneticStrength: Float,
        magneticThreshold: Float,
        targetSpacing: Float,
    ): String {
        val stiffnessStr = fmt(stiffness)
        val dampingStr = fmt(dampingRatio)
        val strengthStr = fmt(magneticStrength, 3)
        val thresholdStr = fmt(magneticThreshold)
        val spacingStr = fmt(targetSpacing)

        return """
            |// Generated by Motion Lab -- drag between snap points with magnetic assist.
            |${ComposeImports.GESTURE}
            |
            |private fun pulledPosition(raw: Float, targetX: Float, threshold: Float, strength: Float): Float {
            |    if (threshold <= 0f) return raw
            |    val distance = kotlin.math.abs(raw - targetX)
            |    if (distance >= threshold) return raw
            |    val pull = (strength * (1f - distance / threshold)).coerceIn(0f, 1f)
            |    return raw + (targetX - raw) * pull
            |}
            |
            |private fun nearestIndex(position: Float, targets: FloatArray): Int {
            |    var bestIndex = 0
            |    var bestDistance = Float.MAX_VALUE
            |    for (i in targets.indices) {
            |        val d = kotlin.math.abs(position - targets[i])
            |        if (d < bestDistance) {
            |            bestDistance = d
            |            bestIndex = i
            |        }
            |    }
            |    return bestIndex
            |}
            |
            |@Composable
            |fun MotionLabMagneticSnap(modifier: Modifier = Modifier) {
            |    val offsetX = remember { Animatable(0f) }
            |    val scope = rememberCoroutineScope()
            |    val targets = floatArrayOf(-${spacingStr}f, 0f, ${spacingStr}f)
            |    val threshold = ${thresholdStr}f
            |    val strength = ${strengthStr}f
            |
            |    Box(
            |        modifier = modifier
            |            .offset { IntOffset(offsetX.value.roundToInt(), 0) }
            |            .pointerInput(Unit) {
            |                var raw = 0f
            |                detectDragGestures(
            |                    onDragStart = { raw = offsetX.value },
            |                    onDrag = { change, dragAmount ->
            |                        change.consume()
            |                        raw += dragAmount.x
            |                        val nearest = targets[nearestIndex(raw, targets)]
            |                        val visual = pulledPosition(raw, nearest, threshold, strength)
            |                        scope.launch { offsetX.snapTo(visual) }
            |                    },
            |                    onDragEnd = {
            |                        val target = targets[nearestIndex(offsetX.value, targets)]
            |                        scope.launch {
            |                            offsetX.animateTo(
            |                                targetValue = target,
            |                                animationSpec = spring(
            |                                    dampingRatio = ${dampingStr}f,
            |                                    stiffness = ${stiffnessStr}f
            |                                )
            |                            )
            |                            // Settled on a target: fire HapticEngine.play(HapticEvent.Snap) here.
            |                        }
            |                    }
            |                )
            |            }
            |    )
            |}
        """.trimMargin()
    }

    private fun fmt(value: Float, decimals: Int = 1): String {
        val factor = Math.pow(10.0, decimals.toDouble())
        val rounded = round(value * factor) / factor
        return if (decimals == 0) rounded.toInt().toString() else rounded.toString()
    }
}
