package com.motionlab.app.export

import com.motionlab.app.data.MotionTokenEntity
import org.json.JSONObject

/** One shared set of named springs, in the format each platform's code or design tool wants. */
object MotionTokenExporter {

    enum class Format(val label: String) { JSON("Design tokens (JSON)"), SWIFT("SwiftUI"), KOTLIN("Kotlin"), CSS("CSS"), TYPESCRIPT("TypeScript") }

    private fun damping(t: MotionTokenEntity) = SpringMath.damping(t.stiffness, t.dampingRatio)
    private fun n(v: Float, d: Int = 2) = DesignSpec.num(v, d)

    fun slug(name: String) = name.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-').ifEmpty { "spring" }
    /** Words no target language lets you use as a bare name (union of Kotlin, Swift and TypeScript). */
    private val RESERVED = setOf(
        "as", "break", "case", "catch", "class", "const", "continue", "default", "defer", "delete", "do", "else", "enum", "export",
        "extends", "extension", "false", "final", "finally", "for", "fun", "func", "function", "guard", "if", "import", "in", "init",
        "interface", "internal", "is", "let", "new", "nil", "null", "object", "open", "operator", "override", "package", "private",
        "protocol", "public", "repeat", "return", "self", "static", "struct", "subscript", "super", "switch", "this", "throw", "true",
        "try", "typealias", "typeof", "val", "var", "void", "when", "where", "while", "with", "yield",
    )

    /** A valid identifier in Kotlin, Swift and TypeScript: no leading digit, no reserved word. */
    fun camel(name: String): String {
        val parts = slug(name).split('-')
        val id = parts.first() + parts.drop(1).joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
        return when {
            id[0].isDigit() -> "_$id"
            id in RESERVED -> "${id}Spring"
            else -> id
        }
    }

    /** One identifier per token, with 2, 3... added when two names collapse to the same one, so no token overwrites another. */
    private fun unique(names: List<String>): List<String> {
        val seen = HashMap<String, Int>()
        return names.map { n ->
            val c = (seen[n] ?: 0) + 1
            seen[n] = c
            if (c == 1) n else "$n$c"
        }
    }

    private fun ids(tokens: List<MotionTokenEntity>) = unique(tokens.map { camel(it.name) })
    private fun slugs(tokens: List<MotionTokenEntity>) = unique(tokens.map { slug(it.name) })

    /** Every code format is stamped (see [ExportStamp]) so the shipped file can later be checked against these tokens. JSON can't carry comments. */
    fun export(tokens: List<MotionTokenEntity>, format: Format): String {
        val raw = raw(tokens, format)
        val style = when (format) {
            Format.JSON -> return raw
            Format.CSS -> ExportStamp.Style.BLOCK
            else -> ExportStamp.Style.SLASH
        }
        return ExportStamp.wrap(raw, style, tokens.map { ExportStamp.Spring("t", it.name, it.stiffness, it.dampingRatio) })
    }

    private fun raw(tokens: List<MotionTokenEntity>, format: Format): String {
        val id = ids(tokens)
        val slug = slugs(tokens)
        fun lines(build: (Int, MotionTokenEntity) -> String) = tokens.withIndex().joinToString("\n") { (i, t) -> build(i, t) }
        return when (format) {
            Format.JSON -> json(tokens)
            Format.SWIFT -> "// Generated by Motion Lab\nimport SwiftUI\n\nextension Animation {\n" +
                lines { i, t -> "    static let ${id[i]} = Animation.interpolatingSpring(mass: 1, stiffness: ${n(t.stiffness, 1)}, damping: ${n(damping(t))})" } + "\n}\n"
            Format.KOTLIN -> "// Generated by Motion Lab\nimport androidx.compose.animation.core.spring\n\nobject MotionTokens {\n" +
                lines { i, t -> "    fun ${id[i]}() = spring<Float>(dampingRatio = ${n(t.dampingRatio)}f, stiffness = ${n(t.stiffness, 1)}f)" } + "\n}\n"
            Format.CSS -> "/* Generated by Motion Lab */\n:root {\n" +
                lines { i, t -> "  --motion-${slug[i]}-duration: ${SpringMath.settleMs(t.stiffness, t.dampingRatio)}ms;\n  --motion-${slug[i]}-easing: ${DesignSpec.cssLinear(t.stiffness, t.dampingRatio)};" } + "\n}\n"
            Format.TYPESCRIPT -> "// Generated by Motion Lab\nexport const motion = {\n" +
                lines { i, t -> "  ${id[i]}: { type: \"spring\", stiffness: ${n(t.stiffness, 1)}, damping: ${n(damping(t))}, mass: 1 }," } + "\n} as const;\n"
        }
    }

    /** W3C-design-tokens flavoured: `$type` / `$value`, one group named "motion". */
    fun json(tokens: List<MotionTokenEntity>): String {
        val group = JSONObject()
        val keys = slugs(tokens)
        tokens.forEachIndexed { i, it ->
            group.put(
                keys[i],
                JSONObject().put("\$type", "spring").put(
                    "\$value",
                    JSONObject().put("mass", 1).put("stiffness", n(it.stiffness, 1).toDouble()).put("damping", n(damping(it)).toDouble())
                        .put("dampingRatio", n(it.dampingRatio).toDouble()).put("settleMs", SpringMath.settleMs(it.stiffness, it.dampingRatio))
                )
            )
        }
        return JSONObject().put("motion", group).toString(2)
    }
}
