package com.motionlab.app.export

import com.motionlab.app.data.MotionTokenEntity
import org.json.JSONObject

/** One shared set of named springs, in the format each platform's code or design tool wants. */
object MotionTokenExporter {

    enum class Format(val label: String) { JSON("Design tokens (JSON)"), SWIFT("SwiftUI"), KOTLIN("Kotlin"), CSS("CSS"), TYPESCRIPT("TypeScript") }

    private fun damping(t: MotionTokenEntity) = SpringMath.damping(t.stiffness, t.dampingRatio)
    private fun n(v: Float, d: Int = 2) = DesignSpec.num(v, d)

    fun slug(name: String) = name.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-').ifEmpty { "spring" }
    fun camel(name: String): String {
        val parts = slug(name).split('-')
        return parts.first() + parts.drop(1).joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
    }

    /** Every code format is stamped (see [ExportStamp]) so the shipped file can later be checked against these tokens. JSON can't carry comments. */
    fun export(tokens: List<MotionTokenEntity>, format: Format): String {
        val raw = raw(tokens, format)
        val style = when (format) {
            Format.JSON -> return raw
            Format.CSS -> ExportStamp.Style.BLOCK
            else -> ExportStamp.Style.SLASH
        }
        return ExportStamp.wrap(raw, style, tokens.map { ExportStamp.Spring("t", it.name, it.stiffness, it.dampingRatio) })
    }

    private fun raw(tokens: List<MotionTokenEntity>, format: Format): String = when (format) {
        Format.JSON -> json(tokens)
        Format.SWIFT -> "// Generated by Motion Lab\nimport SwiftUI\n\nextension Animation {\n" +
            tokens.joinToString("\n") { "    static let ${camel(it.name)} = Animation.interpolatingSpring(mass: 1, stiffness: ${n(it.stiffness, 1)}, damping: ${n(damping(it))})" } + "\n}\n"
        Format.KOTLIN -> "// Generated by Motion Lab\nimport androidx.compose.animation.core.spring\n\nobject MotionTokens {\n" +
            tokens.joinToString("\n") { "    fun ${camel(it.name)}() = spring<Float>(dampingRatio = ${n(it.dampingRatio)}f, stiffness = ${n(it.stiffness, 1)}f)" } + "\n}\n"
        Format.CSS -> "/* Generated by Motion Lab */\n:root {\n" +
            tokens.joinToString("\n") { "  --motion-${slug(it.name)}-duration: ${SpringMath.settleMs(it.stiffness, it.dampingRatio)}ms;\n  --motion-${slug(it.name)}-easing: ${DesignSpec.cssLinear(it.stiffness, it.dampingRatio)};" } + "\n}\n"
        Format.TYPESCRIPT -> "// Generated by Motion Lab\nexport const motion = {\n" +
            tokens.joinToString("\n") { "  ${camel(it.name)}: { type: \"spring\", stiffness: ${n(it.stiffness, 1)}, damping: ${n(damping(it))}, mass: 1 }," } + "\n} as const;\n"
    }

    /** W3C-design-tokens flavoured: `$type` / `$value`, one group named "motion". */
    fun json(tokens: List<MotionTokenEntity>): String {
        val group = JSONObject()
        tokens.forEach {
            group.put(
                slug(it.name),
                JSONObject().put("\$type", "spring").put(
                    "\$value",
                    JSONObject().put("mass", 1).put("stiffness", n(it.stiffness, 1).toDouble()).put("damping", n(damping(it)).toDouble())
                        .put("dampingRatio", n(it.dampingRatio).toDouble()).put("settleMs", SpringMath.settleMs(it.stiffness, it.dampingRatio))
                )
            )
        }
        return JSONObject().put("motion", group).toString(2)
    }
}
