package com.motionlab.app.export

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. The trigger
 * check and the rubber band are copy-pasted verbatim from
 * [com.motionlab.app.core.physics.PullRefreshSolver] and
 * [com.motionlab.app.core.physics.RubberBand]; the hold is a plain `delay`,
 * the return is a real `spring()`.
 */
object PullRefreshCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        triggerDp: Float,
        holdMs: Float,
        resistanceK: Float,
    ): String {
        val stiffnessStr = DesignSpec.num(stiffness, 1)
        val dampingStr = DesignSpec.num(dampingRatio, 2)
        val triggerStr = DesignSpec.num(triggerDp, 0)
        val holdStr = DesignSpec.num(holdMs, 0)
        val kStr = DesignSpec.num(resistanceK, 4)

        return """
            |// Generated by Motion Lab -- pull to refresh with an elastic pull and a real settle spring.
            |
            |private fun rubberBand(raw: Float, k: Float): Float {
            |    return raw / (1 + k * kotlin.math.abs(raw))
            |}
            |
            |@Composable
            |fun MotionLabPullToRefresh(
            |    onRefresh: suspend () -> Unit,
            |    modifier: Modifier = Modifier,
            |    content: @Composable () -> Unit,
            |) {
            |    val density = LocalDensity.current
            |    val trigger = with(density) { ${triggerStr}.dp.toPx() }
            |    val resistanceK = ${kStr}f
            |    val offsetY = remember { Animatable(0f) }
            |    val scope = rememberCoroutineScope()
            |
            |    Box(
            |        modifier = modifier
            |            .offset { IntOffset(0, offsetY.value.roundToInt()) }
            |            .pointerInput(Unit) {
            |                var raw = 0f
            |                var triggered = false
            |                detectDragGestures(
            |                    onDragStart = { raw = offsetY.value; triggered = false },
            |                    onDrag = { change, dragAmount ->
            |                        change.consume()
            |                        raw += dragAmount.y
            |                        val visual = rubberBand(raw, resistanceK)
            |                        triggered = visual >= trigger
            |                        scope.launch { offsetY.snapTo(visual) }
            |                    },
            |                    onDragEnd = {
            |                        scope.launch {
            |                            if (triggered) {
            |                                offsetY.animateTo(trigger, spring(dampingRatio = ${dampingStr}f, stiffness = ${stiffnessStr}f))
            |                                onRefresh()
            |                                delay(${holdStr}L)
            |                            }
            |                            offsetY.animateTo(0f, spring(dampingRatio = ${dampingStr}f, stiffness = ${stiffnessStr}f))
            |                        }
            |                    },
            |                )
            |            },
            |    ) { content() }
            |}
        """.trimMargin()
    }
}
