package com.motionlab.app.export

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. The swap rule
 * is copy-pasted verbatim from [com.motionlab.app.core.physics.ReorderSolver];
 * the settle is a real `spring()`. Only the dragged row's own displacement is
 * driven by a tunable spring here -- the emitted snippet lets the framework's
 * own list-diffing animate the rest, since that's the idiomatic way to do
 * this outside of Motion Lab's own fixed four-row stage.
 */
object ReorderCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        itemHeightDp: Float,
        thresholdDp: Float,
    ): String {
        val stiffnessStr = DesignSpec.num(stiffness, 1)
        val dampingStr = DesignSpec.num(dampingRatio, 2)
        val heightStr = DesignSpec.num(itemHeightDp, 0)
        val thresholdStr = DesignSpec.num(thresholdDp, 0)

        return """
            |// Generated by Motion Lab -- drag to reorder, swap threshold plus a real settle spring.
            |// Call onReorder(from, to) to apply the swap to your own backing list.
            |
            |private fun slotsMoved(offsetPx: Float, itemHeightPx: Float, thresholdPx: Float): Int {
            |    if (itemHeightPx <= 0f) return 0
            |    val direction = if (offsetPx >= 0f) 1 else -1
            |    val magnitude = kotlin.math.abs(offsetPx)
            |    if (magnitude < thresholdPx) return 0
            |    return direction * (kotlin.math.floor((magnitude - thresholdPx) / itemHeightPx).toInt() + 1)
            |}
            |
            |@Composable
            |fun MotionLabReorderRow(
            |    index: Int,
            |    itemCount: Int,
            |    onReorder: (from: Int, to: Int) -> Unit,
            |    modifier: Modifier = Modifier,
            |    content: @Composable () -> Unit,
            |) {
            |    val density = LocalDensity.current
            |    val itemHeight = with(density) { ${heightStr}.dp.toPx() }
            |    val threshold = with(density) { ${thresholdStr}.dp.toPx() }
            |    val dragY = remember { Animatable(0f) }
            |    val scope = rememberCoroutineScope()
            |
            |    Box(
            |        modifier = modifier
            |            .offset { IntOffset(0, dragY.value.roundToInt()) }
            |            .pointerInput(Unit) {
            |                var raw = 0f
            |                detectDragGestures(
            |                    onDragStart = { raw = dragY.value },
            |                    onDrag = { change, dragAmount ->
            |                        change.consume()
            |                        raw += dragAmount.y
            |                        scope.launch { dragY.snapTo(raw) }
            |                    },
            |                    onDragEnd = {
            |                        val moved = slotsMoved(raw, itemHeight, threshold)
            |                        val target = (index + moved).coerceIn(0, itemCount - 1)
            |                        scope.launch {
            |                            dragY.animateTo(
            |                                (target - index) * itemHeight,
            |                                spring(dampingRatio = ${dampingStr}f, stiffness = ${stiffnessStr}f),
            |                            )
            |                            if (target != index) onReorder(index, target)
            |                            dragY.snapTo(0f)
            |                        }
            |                    },
            |                )
            |            },
            |    ) { content() }
            |}
        """.trimMargin()
    }
}
