package com.motionlab.app.export

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. The settle rule
 * and the resistance above full are copy-pasted verbatim from
 * [com.motionlab.app.core.physics.SheetSolver]; the movement is a real
 * `spring()` with the numbers the live preview uses. Detents are emitted as
 * fractions of the container, so the sheet scales to any screen or parent.
 */
object SheetCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        peekFraction: Float,
        midFraction: Float,
        fullFraction: Float,
        momentumSec: Float,
        dismissLineFraction: Float,
        resistanceK: Float,
    ): String {
        val stiffnessStr = DesignSpec.num(stiffness, 1)
        val dampingStr = DesignSpec.num(dampingRatio, 2)
        val peekStr = DesignSpec.num(peekFraction, 3)
        val midStr = DesignSpec.num(midFraction, 3)
        val fullStr = DesignSpec.num(fullFraction, 3)
        val momentumStr = DesignSpec.num(momentumSec, 3)
        val dismissStr = DesignSpec.num(dismissLineFraction, 3)
        val kStr = DesignSpec.num(resistanceK, 4)

        return """
            |// Generated by Motion Lab -- bottom sheet with detents, momentum and drag-to-dismiss.
            |// Heights are how much of the sheet is showing (0 = hidden), as fractions of its container.
            |
            |private fun settleHeight(height: Float, velocityUp: Float, lookaheadSec: Float, detents: FloatArray, dismissLine: Float): Float {
            |    val target = height + velocityUp * lookaheadSec
            |    if (target < dismissLine) return 0f
            |    var best = detents[0]
            |    for (d in detents) if (kotlin.math.abs(target - d) < kotlin.math.abs(target - best)) best = d
            |    return best
            |}
            |
            |private fun visualHeight(raw: Float, full: Float, k: Float): Float {
            |    if (raw <= full) return raw.coerceAtLeast(0f)
            |    val excess = raw - full
            |    return full + excess / (1 + k * kotlin.math.abs(excess))
            |}
            |
            |@Composable
            |fun MotionLabBottomSheet(
            |    onDismissed: () -> Unit,
            |    modifier: Modifier = Modifier,
            |    content: @Composable ColumnScope.() -> Unit,
            |) {
            |    val density = LocalDensity.current
            |    BoxWithConstraints(modifier.fillMaxSize()) {
            |        val container = with(density) { maxHeight.toPx() }
            |        val peek = container * ${peekStr}f
            |        val detents = floatArrayOf(peek, container * ${midStr}f, container * ${fullStr}f)
            |        val full = detents.last()
            |        val dismissLine = peek * ${dismissStr}f
            |        val revealed = remember { Animatable(peek) }
            |        val scope = rememberCoroutineScope()
            |
            |        Column(
            |            modifier = Modifier
            |                .fillMaxWidth()
            |                .height(maxHeight)
            |                .offset { IntOffset(0, (container - revealed.value).roundToInt()) }
            |                .pointerInput(Unit) {
            |                    var raw = 0f
            |                    val tracker = VelocityTracker()
            |                    detectDragGestures(
            |                        onDragStart = { raw = revealed.value; tracker.resetTracking() },
            |                        onDrag = { change, dragAmount ->
            |                            change.consume()
            |                            raw -= dragAmount.y
            |                            val visual = visualHeight(raw, full, ${kStr}f)
            |                            // Track the height itself: the sheet moves under the finger, so pointer-local positions barely change.
            |                            tracker.addPosition(change.uptimeMillis, Offset(0f, visual))
            |                            scope.launch { revealed.snapTo(visual) }
            |                        },
            |                        onDragEnd = {
            |                            val velocity = tracker.calculateVelocity().y
            |                            val target = settleHeight(revealed.value, velocity, ${momentumStr}f, detents, dismissLine)
            |                            scope.launch {
            |                                revealed.animateTo(
            |                                    targetValue = target,
            |                                    animationSpec = spring(dampingRatio = ${dampingStr}f, stiffness = ${stiffnessStr}f),
            |                                    initialVelocity = velocity,
            |                                )
            |                                if (target == 0f) onDismissed()
            |                            }
            |                        },
            |                    )
            |                },
            |            content = content,
            |        )
            |    }
            |}
        """.trimMargin()
    }
}
