package com.motionlab.app.export

import kotlin.math.round

/**
 * Deterministic Compose code generation (spec §28-29): the same MotionConfig
 * always produces the same Kotlin, byte for byte. No AST/KotlinPoet here on
 * purpose -- these are 10-30 line snippets, not whole files, so a plain
 * template plus fixed-precision formatting is simpler and just as correct,
 * and it's trivial to golden-test string output.
 *
 * IMPORTANT (fidelity guarantee): stiffness/dampingRatio below are the exact
 * Float values fed into the live-preview Animatable's spring() spec in
 * EditorScreen. This function only formats them -- it never recomputes or
 * re-derives them -- so the emitted spring() call reproduces the on-device
 * preview exactly, not an approximation of it.
 */
object SpringCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        resistanceK: Float,
        bound: Float,
    ): String {
        val stiffnessStr = formatFloat(stiffness)
        val dampingStr = formatFloat(dampingRatio)
        val kStr = formatFloat(resistanceK, decimals = 4)
        val boundStr = formatFloat(bound)

        return """
            |// Generated by Motion Lab -- drag-to-spring-back with rubber-band overscroll.
            |// Paste this MotionLabRubberBandDrag() where you'd otherwise hand-roll drag physics.
            |${ComposeImports.GESTURE}
            |
            |private fun rubberBand(raw: Float, bound: Float, k: Float): Float {
            |    val clamped = raw.coerceIn(-bound, bound)
            |    val excess = raw - clamped
            |    return clamped + excess / (1 + k * kotlin.math.abs(excess))
            |}
            |
            |@Composable
            |fun MotionLabRubberBandDrag(modifier: Modifier = Modifier) {
            |    val offsetX = remember { Animatable(0f) }
            |    val scope = rememberCoroutineScope()
            |    val bound = ${boundStr}f
            |    val resistanceK = ${kStr}f
            |
            |    Box(
            |        // offset/scale first, so whatever look you pass in modifier (size, background) moves with it.
            |        modifier = Modifier
            |            .offset { IntOffset(offsetX.value.roundToInt(), 0) }
            |            .then(modifier)
            |            .pointerInput(Unit) {
            |                var raw = 0f
            |                detectDragGestures(
            |                    onDragStart = { raw = offsetX.value },
            |                    onDrag = { change, dragAmount ->
            |                        change.consume()
            |                        raw += dragAmount.x
            |                        scope.launch {
            |                            offsetX.snapTo(rubberBand(raw, bound, resistanceK))
            |                        }
            |                    },
            |                    onDragEnd = {
            |                        scope.launch {
            |                            offsetX.animateTo(
            |                                targetValue = 0f,
            |                                animationSpec = spring(
            |                                    dampingRatio = ${dampingStr}f,
            |                                    stiffness = ${stiffnessStr}f
            |                                )
            |                            )
            |                            // Settled: fire your haptic here, e.g. HapticEngine.play(HapticEvent.Release)
            |                        }
            |                    }
            |                )
            |            }
            |    )
            |}
        """.trimMargin()
    }

    private fun formatFloat(value: Float, decimals: Int = 1): String {
        val factor = Math.pow(10.0, decimals.toDouble())
        val rounded = round(value * factor) / factor
        return if (decimals == 0) rounded.toInt().toString() else rounded.toString()
    }
}
