package com.motionlab.app.export

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. The dismissal
 * decision and tilt are copy-pasted verbatim from
 * [com.motionlab.app.core.physics.SwipeSolver]; the fling is Compose's own
 * `exponentialDecay` and the return is `spring()`, fed the same numbers the
 * live preview uses. Distances are emitted in dp and converted at runtime, so
 * the feel holds across screen densities.
 */
object SwipeCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        distanceDp: Float,
        velocityDpPerSec: Float,
        friction: Float,
        tiltDegrees: Float,
    ): String {
        val stiffnessStr = DesignSpec.num(stiffness, 1)
        val dampingStr = DesignSpec.num(dampingRatio, 2)
        val distanceStr = DesignSpec.num(distanceDp, 0)
        val velocityStr = DesignSpec.num(velocityDpPerSec, 0)
        val frictionStr = DesignSpec.num(friction, 2)
        val tiltStr = DesignSpec.num(tiltDegrees, 1)

        return """
            |// Generated by Motion Lab -- swipe to dismiss with a real fling.
            |// onDismissed gets -1 (left) or +1 (right); remove the card there.
            |${ComposeImports.GESTURE}
            |
            |private fun dismissDirection(offset: Float, velocity: Float, distance: Float, velocityThreshold: Float): Int {
            |    if (kotlin.math.abs(velocity) >= velocityThreshold) return if (velocity > 0f) 1 else -1
            |    if (kotlin.math.abs(offset) >= distance) return if (offset > 0f) 1 else -1
            |    return 0
            |}
            |
            |private fun tiltDegrees(offset: Float, distance: Float, maxTilt: Float): Float =
            |    maxTilt * (offset / (distance * 3f)).coerceIn(-1f, 1f)
            |
            |@Composable
            |fun MotionLabSwipeCard(
            |    onDismissed: (direction: Int) -> Unit,
            |    modifier: Modifier = Modifier,
            |    content: @Composable () -> Unit,
            |) {
            |    val density = LocalDensity.current
            |    val distance = with(density) { ${distanceStr}.dp.toPx() }
            |    val velocityThreshold = with(density) { ${velocityStr}.dp.toPx() }
            |    val exitDistance = with(density) { LocalConfiguration.current.screenWidthDp.dp.toPx() }
            |    val maxTilt = ${tiltStr}f
            |    val friction = ${frictionStr}f
            |    val offsetX = remember { Animatable(0f) }
            |    val scope = rememberCoroutineScope()
            |
            |    Box(
            |        // offset/scale first, so whatever look you pass in modifier (size, background) moves with it.
            |        modifier = Modifier
            |            .offset { IntOffset(offsetX.value.roundToInt(), 0) }
            |            .graphicsLayer { rotationZ = tiltDegrees(offsetX.value, distance, maxTilt) }
            |            .then(modifier)
            |            .pointerInput(Unit) {
            |                var raw = 0f
            |                val tracker = VelocityTracker()
            |                detectDragGestures(
            |                    onDragStart = { raw = offsetX.value; tracker.resetTracking() },
            |                    onDrag = { change, dragAmount ->
            |                        change.consume()
            |                        raw += dragAmount.x
            |                        tracker.addPosition(change.uptimeMillis, Offset(raw, 0f)) // not change.position: that moves with the card and reads ~0
            |                        scope.launch { offsetX.snapTo(raw) }
            |                    },
            |                    onDragEnd = {
            |                        val velocity = tracker.calculateVelocity().x
            |                        val direction = dismissDirection(offsetX.value, velocity, distance, velocityThreshold)
            |                        scope.launch {
            |                            if (direction == 0) {
            |                                offsetX.animateTo(
            |                                    targetValue = 0f,
            |                                    animationSpec = spring(dampingRatio = ${dampingStr}f, stiffness = ${stiffnessStr}f),
            |                                    initialVelocity = velocity,
            |                                )
            |                            } else {
            |                                // A slow release past the distance is thrown at the threshold speed.
            |                                val launch = if (kotlin.math.abs(velocity) >= velocityThreshold) velocity else direction * velocityThreshold
            |                                offsetX.animateDecay(launch, exponentialDecay(frictionMultiplier = friction))
            |                                if (kotlin.math.abs(offsetX.value) < exitDistance) {
            |                                    offsetX.animateTo(direction * exitDistance, tween(160))
            |                                }
            |                                onDismissed(direction)
            |                            }
            |                        }
            |                    },
            |                )
            |            },
            |    ) { content() }
            |}
        """.trimMargin()
    }
}
