package com.motionlab.app.export

/**
 * Same deterministic-template policy as [SpringCodeGenerator]. The bounded
 * rubber-band is copy-pasted verbatim from [com.motionlab.app.core.physics.ZoomSolver];
 * the release is a real `spring()`, always back to 1x -- see that solver's
 * doc comment for why every interaction here ends at a real rest state.
 */
object ZoomCodeGenerator {

    fun generate(
        stiffness: Float,
        dampingRatio: Float,
        minScale: Float,
        maxScale: Float,
        resistanceK: Float,
    ): String {
        val stiffnessStr = DesignSpec.num(stiffness, 1)
        val dampingStr = DesignSpec.num(dampingRatio, 2)
        val minStr = DesignSpec.num(minScale, 3)
        val maxStr = DesignSpec.num(maxScale, 3)
        val kStr = DesignSpec.num(resistanceK, 4)

        return """
            |// Generated by Motion Lab -- pinch to zoom, rubber-banded past its bounds, always releases back to 1x.
            |${ComposeImports.GESTURE}
            |
            |private fun visualScale(raw: Float, min: Float, max: Float, k: Float): Float {
            |    fun rubberBand(excess: Float) = excess / (1 + k * kotlin.math.abs(excess))
            |    return when {
            |        raw > max -> max + rubberBand(raw - max)
            |        raw < min -> (min - rubberBand(min - raw)).coerceAtLeast(0f)
            |        else -> raw
            |    }
            |}
            |
            |@Composable
            |fun MotionLabPinchZoom(modifier: Modifier = Modifier, content: @Composable () -> Unit) {
            |    val min = ${minStr}f
            |    val max = ${maxStr}f
            |    val resistanceK = ${kStr}f
            |    val scale = remember { Animatable(1f) }
            |    val scope = rememberCoroutineScope()
            |
            |    Box(
            |        modifier = modifier
            |            .graphicsLayer { scaleX = scale.value; scaleY = scale.value }
            |            .pointerInput(Unit) {
            |                while (true) {
            |                    var raw = scale.value
            |                    detectTransformGestures { _, _, zoom, _ ->
            |                        raw *= zoom
            |                        val visual = visualScale(raw, min, max, resistanceK)
            |                        scope.launch { scale.snapTo(visual) }
            |                    }
            |                    scope.launch {
            |                        scale.animateTo(1f, spring(dampingRatio = ${dampingStr}f, stiffness = ${stiffnessStr}f))
            |                    }
            |                }
            |            },
            |    ) { content() }
            |}
        """.trimMargin()
    }
}
