package com.motionlab.app.data

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

@Dao
interface TimelineDao {
    @Query("SELECT * FROM timelines ORDER BY updatedAt DESC")
    fun observeAll(): Flow<List<TimelineEntity>>

    @Query("SELECT * FROM timelines WHERE id = :id")
    suspend fun getById(id: Long): TimelineEntity?

    @Query("SELECT COUNT(*) FROM timelines")
    suspend fun count(): Int

    /**
     * For a brand-new row only (id = 0, autogenerated). [OnConflictStrategy.REPLACE]
     * is SQLite's delete-then-reinsert: calling this on an *existing* timeline
     * would cascade-delete every one of its steps (they reference it with an
     * `ON DELETE CASCADE` foreign key). Updating an existing row must go
     * through [update] instead -- this bit a first version of this DAO, caught
     * by TimelineRepositoryInstrumentedTest, not by inspection.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(entity: TimelineEntity): Long

    @Update
    suspend fun update(entity: TimelineEntity)

    @Delete
    suspend fun delete(entity: TimelineEntity)

    @Query("SELECT * FROM timeline_steps WHERE timelineId = :timelineId ORDER BY position ASC")
    fun observeSteps(timelineId: Long): Flow<List<TimelineStepEntity>>

    @Query("SELECT * FROM timeline_steps WHERE timelineId = :timelineId ORDER BY position ASC")
    suspend fun getSteps(timelineId: Long): List<TimelineStepEntity>

    /** For a brand-new step only (id = 0) -- same REPLACE caveat as [upsert]; use [updateStep] on an existing one. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertStep(step: TimelineStepEntity): Long

    @Update
    suspend fun updateStep(step: TimelineStepEntity)

    @Delete
    suspend fun deleteStep(step: TimelineStepEntity)

    @Query("SELECT * FROM timeline_haptics WHERE timelineId = :timelineId ORDER BY timeMs ASC, id ASC")
    fun observeHaptics(timelineId: Long): Flow<List<TimelineHapticEntity>>

    /** New marker only (id = 0) -- same REPLACE caveat as [upsert]. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertHaptic(marker: TimelineHapticEntity): Long

    @Update
    suspend fun updateHaptic(marker: TimelineHapticEntity)

    @Delete
    suspend fun deleteHaptic(marker: TimelineHapticEntity)
}
